// GENERATED by scripts/import-assets.mjs — do not edit by hand.
import type { GeneratedCollection } from "./collection-types";

/** Collection slugs the Indexer serves, as of the last import. */
export const INDEXER_COLLECTIONS: string[] = ["pig-mud","piggy-gang","piggy-girl-gang","piggy-sol-gang"];

export const GENERATED: Record<string, GeneratedCollection> = {
  "piggy-sol-gang": {
    "slug": "piggy-sol-gang",
    "supply": 10000,
    "canvas": 1080,
    "bodyCategoryId": "body",
    "mannequinBody": "salmon",
    "categories": [
      {
        "id": "background",
        "label": "Background",
        "metaName": "Background",
        "dir": "background",
        "optional": false,
        "noneCount": 0,
        "focus": {
          "x": 0,
          "y": 0,
          "w": 1,
          "h": 1
        },
        "traits": [
          {
            "name": "Red",
            "slug": "red",
            "count": 1486,
            "ext": "png"
          },
          {
            "name": "Purple",
            "slug": "purple",
            "count": 1456,
            "ext": "png"
          },
          {
            "name": "Yellow",
            "slug": "yellow",
            "count": 1436,
            "ext": "png"
          },
          {
            "name": "Cyan",
            "slug": "cyan",
            "count": 1433,
            "ext": "png"
          },
          {
            "name": "Blue",
            "slug": "blue",
            "count": 1418,
            "ext": "png"
          },
          {
            "name": "Orange",
            "slug": "orange",
            "count": 1390,
            "ext": "png"
          },
          {
            "name": "Green",
            "slug": "green",
            "count": 1381,
            "ext": "png"
          }
        ]
      },
      {
        "id": "body",
        "label": "Skin",
        "metaName": "Body",
        "dir": "body",
        "optional": false,
        "noneCount": 0,
        "focus": {
          "x": 0,
          "y": 0.0034,
          "w": 0.9966,
          "h": 0.9966
        },
        "traits": [
          {
            "name": "Salmon",
            "slug": "salmon",
            "count": 3844,
            "ext": "png"
          },
          {
            "name": "Pink",
            "slug": "pink",
            "count": 2237,
            "ext": "png"
          },
          {
            "name": "Purple",
            "slug": "purple",
            "count": 1609,
            "ext": "png"
          },
          {
            "name": "Yellow",
            "slug": "yellow",
            "count": 1406,
            "ext": "png"
          },
          {
            "name": "Zombie",
            "slug": "zombie",
            "count": 468,
            "ext": "png"
          },
          {
            "name": "Alien",
            "slug": "alien",
            "count": 293,
            "ext": "png"
          },
          {
            "name": "Solana",
            "slug": "solana",
            "count": 143,
            "ext": "png"
          }
        ]
      },
      {
        "id": "clothes",
        "label": "Clothes",
        "metaName": "Clothes",
        "dir": "clothes",
        "optional": true,
        "noneCount": 653,
        "focus": {
          "x": 0.1287,
          "y": 0.2445,
          "w": 0.7555,
          "h": 0.7555
        },
        "traits": [
          {
            "name": "Singlet",
            "slug": "singlet",
            "count": 1438,
            "ext": "png"
          },
          {
            "name": "Piggy Tee",
            "slug": "piggy-tee",
            "count": 1361,
            "ext": "png"
          },
          {
            "name": "Fancy Sweater",
            "slug": "fancy-sweater",
            "count": 1162,
            "ext": "png"
          },
          {
            "name": "Red Jacket",
            "slug": "red-jacket",
            "count": 832,
            "ext": "png"
          },
          {
            "name": "Pink Leather Jacket",
            "slug": "pink-leather-jacket",
            "count": 821,
            "ext": "png"
          },
          {
            "name": "Purple Shirt",
            "slug": "purple-shirt",
            "count": 720,
            "ext": "png"
          },
          {
            "name": "Artist Apron",
            "slug": "artist-apron",
            "count": 718,
            "ext": "png"
          },
          {
            "name": "Star Tee",
            "slug": "star-tee",
            "count": 668,
            "ext": "png"
          },
          {
            "name": "Bone Necklace",
            "slug": "bone-necklace",
            "count": 555,
            "ext": "png"
          },
          {
            "name": "Rich Jacket",
            "slug": "rich-jacket",
            "count": 427,
            "ext": "png"
          },
          {
            "name": "Pocket Watch",
            "slug": "pocket-watch",
            "count": 293,
            "ext": "png"
          },
          {
            "name": "Blanket",
            "slug": "blanket",
            "count": 201,
            "ext": "png"
          },
          {
            "name": "Solana Tee",
            "slug": "solana-tee",
            "count": 151,
            "ext": "png"
          }
        ]
      },
      {
        "id": "eyes",
        "label": "Eyes",
        "metaName": "Eyes",
        "dir": "eyes",
        "optional": false,
        "noneCount": 0,
        "focus": {
          "x": 0.0539,
          "y": 0,
          "w": 0.9461,
          "h": 0.9461
        },
        "traits": [
          {
            "name": "Open",
            "slug": "open",
            "count": 1176,
            "ext": "png"
          },
          {
            "name": "Beaten",
            "slug": "beaten",
            "count": 976,
            "ext": "png"
          },
          {
            "name": "Closed",
            "slug": "closed",
            "count": 968,
            "ext": "png"
          },
          {
            "name": "Crying",
            "slug": "crying",
            "count": 758,
            "ext": "png"
          },
          {
            "name": "High",
            "slug": "high",
            "count": 712,
            "ext": "png"
          },
          {
            "name": "Wink",
            "slug": "wink",
            "count": 702,
            "ext": "png"
          },
          {
            "name": "Sleeping",
            "slug": "sleeping",
            "count": 690,
            "ext": "png"
          },
          {
            "name": "Focused",
            "slug": "focused",
            "count": 680,
            "ext": "png"
          },
          {
            "name": "Coin",
            "slug": "coin",
            "count": 668,
            "ext": "png"
          },
          {
            "name": "Hypnotize",
            "slug": "hypnotize",
            "count": 575,
            "ext": "png"
          },
          {
            "name": "Monocle",
            "slug": "monocle",
            "count": 489,
            "ext": "png"
          },
          {
            "name": "Heart Eyes",
            "slug": "heart-eyes",
            "count": 486,
            "ext": "png"
          },
          {
            "name": "Star Eyes",
            "slug": "star-eyes",
            "count": 478,
            "ext": "png"
          },
          {
            "name": "Dollar Sign Googles",
            "slug": "dollar-sign-googles",
            "count": 246,
            "ext": "png"
          },
          {
            "name": "3d Glasses",
            "slug": "3d-glasses",
            "count": 245,
            "ext": "png"
          },
          {
            "name": "Laser",
            "slug": "laser",
            "count": 151,
            "ext": "png"
          }
        ]
      },
      {
        "id": "mouth",
        "label": "Mouth",
        "metaName": "Mouth",
        "dir": "mouth",
        "optional": false,
        "noneCount": 0,
        "focus": {
          "x": 0.3614,
          "y": 0.3966,
          "w": 0.5523,
          "h": 0.5523
        },
        "traits": [
          {
            "name": "Smiling",
            "slug": "smiling",
            "count": 1506,
            "ext": "png"
          },
          {
            "name": "Neutral",
            "slug": "neutral",
            "count": 1501,
            "ext": "png"
          },
          {
            "name": "Annoyed",
            "slug": "annoyed",
            "count": 1096,
            "ext": "png"
          },
          {
            "name": "Beaten",
            "slug": "beaten",
            "count": 1035,
            "ext": "png"
          },
          {
            "name": "Cigarette",
            "slug": "cigarette",
            "count": 870,
            "ext": "png"
          },
          {
            "name": "Weed",
            "slug": "weed",
            "count": 846,
            "ext": "png"
          },
          {
            "name": "Bubble Gum",
            "slug": "bubble-gum",
            "count": 831,
            "ext": "png"
          },
          {
            "name": "Lick",
            "slug": "lick",
            "count": 683,
            "ext": "png"
          },
          {
            "name": "Biting Brush",
            "slug": "biting-brush",
            "count": 585,
            "ext": "png"
          },
          {
            "name": "Braces",
            "slug": "braces",
            "count": 448,
            "ext": "png"
          },
          {
            "name": "Party Horn",
            "slug": "party-horn",
            "count": 433,
            "ext": "png"
          },
          {
            "name": "Golden Teeth",
            "slug": "golden-teeth",
            "count": 166,
            "ext": "png"
          }
        ]
      },
      {
        "id": "head",
        "label": "Headwear",
        "metaName": "Head",
        "dir": "head",
        "optional": true,
        "noneCount": 581,
        "focus": {
          "x": 0.1642,
          "y": 0,
          "w": 0.7141,
          "h": 0.7141
        },
        "traits": [
          {
            "name": "Beanie",
            "slug": "beanie",
            "count": 846,
            "ext": "png"
          },
          {
            "name": "Beret",
            "slug": "beret",
            "count": 749,
            "ext": "png"
          },
          {
            "name": "Cowboy Hat",
            "slug": "cowboy-hat",
            "count": 631,
            "ext": "png"
          },
          {
            "name": "Fedora",
            "slug": "fedora",
            "count": 575,
            "ext": "png"
          },
          {
            "name": "Officer Cap",
            "slug": "officer-cap",
            "count": 561,
            "ext": "png"
          },
          {
            "name": "Santa Cap",
            "slug": "santa-cap",
            "count": 554,
            "ext": "png"
          },
          {
            "name": "Fisherman Hat",
            "slug": "fisherman-hat",
            "count": 541,
            "ext": "png"
          },
          {
            "name": "Elf Hat",
            "slug": "elf-hat",
            "count": 531,
            "ext": "png"
          },
          {
            "name": "Afro Tail",
            "slug": "afro-tail",
            "count": 528,
            "ext": "png"
          },
          {
            "name": "Fez",
            "slug": "fez",
            "count": 525,
            "ext": "png"
          },
          {
            "name": "Sailor Cap",
            "slug": "sailor-cap",
            "count": 496,
            "ext": "png"
          },
          {
            "name": "Mohawk Hair",
            "slug": "mohawk-hair",
            "count": 470,
            "ext": "png"
          },
          {
            "name": "Leprechaun Hat",
            "slug": "leprechaun-hat",
            "count": 443,
            "ext": "png"
          },
          {
            "name": "Spiky Hair",
            "slug": "spiky-hair",
            "count": 348,
            "ext": "png"
          },
          {
            "name": "Mushroom",
            "slug": "mushroom",
            "count": 329,
            "ext": "png"
          },
          {
            "name": "Party Hat",
            "slug": "party-hat",
            "count": 232,
            "ext": "png"
          },
          {
            "name": "Red Hair",
            "slug": "red-hair",
            "count": 231,
            "ext": "png"
          },
          {
            "name": "Afro Hair",
            "slug": "afro-hair",
            "count": 223,
            "ext": "png"
          },
          {
            "name": "Propeller Hat",
            "slug": "propeller-hat",
            "count": 214,
            "ext": "png"
          },
          {
            "name": "Halo",
            "slug": "halo",
            "count": 122,
            "ext": "png"
          },
          {
            "name": "Unicorn",
            "slug": "unicorn",
            "count": 110,
            "ext": "png"
          },
          {
            "name": "Ice Cream",
            "slug": "ice-cream",
            "count": 109,
            "ext": "png"
          },
          {
            "name": "Royal Crown",
            "slug": "royal-crown",
            "count": 51,
            "ext": "png"
          }
        ]
      },
      {
        "id": "earring",
        "label": "Earring",
        "metaName": "Earring",
        "dir": "earring",
        "optional": true,
        "noneCount": 2380,
        "focus": {
          "x": 0,
          "y": 0.2632,
          "w": 0.5523,
          "h": 0.5523
        },
        "traits": [
          {
            "name": "Amulet",
            "slug": "amulet",
            "count": 1021,
            "ext": "png"
          },
          {
            "name": "Earth",
            "slug": "earth",
            "count": 1002,
            "ext": "png"
          },
          {
            "name": "Western",
            "slug": "western",
            "count": 1002,
            "ext": "png"
          },
          {
            "name": "Palette",
            "slug": "palette",
            "count": 999,
            "ext": "png"
          },
          {
            "name": "Weed",
            "slug": "weed",
            "count": 936,
            "ext": "png"
          },
          {
            "name": "Kiss",
            "slug": "kiss",
            "count": 810,
            "ext": "png"
          },
          {
            "name": "Gun",
            "slug": "gun",
            "count": 611,
            "ext": "png"
          },
          {
            "name": "Gold Ring",
            "slug": "gold-ring",
            "count": 604,
            "ext": "png"
          },
          {
            "name": "Red Diamond",
            "slug": "red-diamond",
            "count": 435,
            "ext": "png"
          },
          {
            "name": "Solana",
            "slug": "solana",
            "count": 200,
            "ext": "png"
          }
        ]
      }
    ],
    "stack": [
      {
        "kind": "category",
        "categoryId": "background"
      },
      {
        "kind": "category",
        "categoryId": "body"
      },
      {
        "kind": "category",
        "categoryId": "clothes"
      },
      {
        "kind": "derived",
        "dir": "body-right-ear",
        "fromCategoryId": "body"
      },
      {
        "kind": "derived",
        "dir": "body-head",
        "fromCategoryId": "body"
      },
      {
        "kind": "category",
        "categoryId": "head"
      },
      {
        "kind": "derived",
        "dir": "body-left-ear",
        "fromCategoryId": "body"
      },
      {
        "kind": "category",
        "categoryId": "eyes"
      },
      {
        "kind": "category",
        "categoryId": "earring"
      },
      {
        "kind": "category",
        "categoryId": "mouth"
      }
    ],
    "codeOrder": [
      "background",
      "body",
      "clothes",
      "earring",
      "eyes",
      "head",
      "mouth"
    ],
    "codeHash": "c4f45d9df696",
    "defaultLook": "0010010",
    "heroLook": "56D97JB",
    "rarityCurve": [
      5.578,
      6.039,
      6.139,
      6.203,
      6.246,
      6.288,
      6.327,
      6.357,
      6.387,
      6.41,
      6.436,
      6.46,
      6.48,
      6.503,
      6.524,
      6.546,
      6.57,
      6.588,
      6.605,
      6.622,
      6.64,
      6.655,
      6.67,
      6.686,
      6.703,
      6.718,
      6.732,
      6.744,
      6.756,
      6.769,
      6.781,
      6.796,
      6.811,
      6.821,
      6.834,
      6.846,
      6.86,
      6.875,
      6.888,
      6.901,
      6.914,
      6.926,
      6.939,
      6.95,
      6.963,
      6.976,
      6.987,
      7.001,
      7.013,
      7.027,
      7.038,
      7.051,
      7.065,
      7.078,
      7.092,
      7.108,
      7.121,
      7.135,
      7.15,
      7.165,
      7.179,
      7.195,
      7.211,
      7.227,
      7.239,
      7.255,
      7.27,
      7.287,
      7.303,
      7.318,
      7.335,
      7.351,
      7.369,
      7.386,
      7.407,
      7.422,
      7.442,
      7.463,
      7.485,
      7.507,
      7.531,
      7.554,
      7.578,
      7.601,
      7.625,
      7.653,
      7.684,
      7.716,
      7.753,
      7.787,
      7.823,
      7.863,
      7.911,
      7.949,
      8.005,
      8.063,
      8.137,
      8.244,
      8.388,
      8.559,
      10.501
    ],
    "tokens": {
      "path": "/piggy/piggy-sol-gang/tokens.txt",
      "stride": 10,
      "firstId": 1,
      "count": 10000
    }
  },
  "piggy-girl-gang": {
    "slug": "piggy-girl-gang",
    "supply": 5000,
    "canvas": 1080,
    "bodyCategoryId": "body",
    "mannequinBody": "salmon",
    "categories": [
      {
        "id": "background",
        "label": "Background",
        "metaName": "Background",
        "dir": "background",
        "optional": false,
        "noneCount": 0,
        "focus": {
          "x": 0,
          "y": 0,
          "w": 1,
          "h": 1
        },
        "traits": [
          {
            "name": "Cyan",
            "slug": "cyan",
            "count": 1222,
            "ext": "png"
          },
          {
            "name": "Yellow",
            "slug": "yellow",
            "count": 1086,
            "ext": "png"
          },
          {
            "name": "Green",
            "slug": "green",
            "count": 585,
            "ext": "png"
          },
          {
            "name": "Blue",
            "slug": "blue",
            "count": 583,
            "ext": "png"
          },
          {
            "name": "Purple",
            "slug": "purple",
            "count": 526,
            "ext": "png"
          },
          {
            "name": "Red",
            "slug": "red",
            "count": 521,
            "ext": "png"
          },
          {
            "name": "Orange",
            "slug": "orange",
            "count": 477,
            "ext": "png"
          }
        ]
      },
      {
        "id": "body",
        "label": "Skin",
        "metaName": "Body",
        "dir": "body",
        "optional": false,
        "noneCount": 0,
        "focus": {
          "x": 0.0292,
          "y": 0.0436,
          "w": 0.9564,
          "h": 0.9564
        },
        "traits": [
          {
            "name": "Salmon",
            "slug": "salmon",
            "count": 1689,
            "ext": "png"
          },
          {
            "name": "Purple",
            "slug": "purple",
            "count": 987,
            "ext": "png"
          },
          {
            "name": "Pink",
            "slug": "pink",
            "count": 946,
            "ext": "png"
          },
          {
            "name": "Yellow",
            "slug": "yellow",
            "count": 818,
            "ext": "png"
          },
          {
            "name": "Zombie",
            "slug": "zombie",
            "count": 311,
            "ext": "png"
          },
          {
            "name": "Alien",
            "slug": "alien",
            "count": 143,
            "ext": "png"
          },
          {
            "name": "Solana",
            "slug": "solana",
            "count": 106,
            "ext": "png"
          }
        ]
      },
      {
        "id": "clothes",
        "label": "Clothes",
        "metaName": "Clothes",
        "dir": "clothes",
        "optional": false,
        "noneCount": 0,
        "focus": {
          "x": 0.1645,
          "y": 0.2698,
          "w": 0.7302,
          "h": 0.7302
        },
        "traits": [
          {
            "name": "Blue Shirt",
            "slug": "blue-shirt",
            "count": 539,
            "ext": "png"
          },
          {
            "name": "Green Dress",
            "slug": "green-dress",
            "count": 459,
            "ext": "png"
          },
          {
            "name": "Pink Dress",
            "slug": "pink-dress",
            "count": 436,
            "ext": "png"
          },
          {
            "name": "Teal Dress",
            "slug": "teal-dress",
            "count": 420,
            "ext": "png"
          },
          {
            "name": "Orange Dress",
            "slug": "orange-dress",
            "count": 418,
            "ext": "png"
          },
          {
            "name": "Red Dress",
            "slug": "red-dress",
            "count": 397,
            "ext": "png"
          },
          {
            "name": "Cyan Dress",
            "slug": "cyan-dress",
            "count": 358,
            "ext": "png"
          },
          {
            "name": "Pink Leather Jacket",
            "slug": "pink-leather-jacket",
            "count": 352,
            "ext": "png"
          },
          {
            "name": "Strawberry Dress",
            "slug": "strawberry-dress",
            "count": 296,
            "ext": "png"
          },
          {
            "name": "Dark Green Dress",
            "slug": "dark-green-dress",
            "count": 276,
            "ext": "png"
          },
          {
            "name": "Farmer",
            "slug": "farmer",
            "count": 263,
            "ext": "png"
          },
          {
            "name": "Dollar Necklace",
            "slug": "dollar-necklace",
            "count": 227,
            "ext": "png"
          },
          {
            "name": "Bridal Gown",
            "slug": "bridal-gown",
            "count": 117,
            "ext": "png"
          },
          {
            "name": "Yellow Bikini",
            "slug": "yellow-bikini",
            "count": 104,
            "ext": "png"
          },
          {
            "name": "Blue Bikini",
            "slug": "blue-bikini",
            "count": 77,
            "ext": "png"
          },
          {
            "name": "Flame Bikini",
            "slug": "flame-bikini",
            "count": 73,
            "ext": "png"
          },
          {
            "name": "Nurse",
            "slug": "nurse",
            "count": 70,
            "ext": "png"
          },
          {
            "name": "Purple Bikini",
            "slug": "purple-bikini",
            "count": 69,
            "ext": "png"
          },
          {
            "name": "Solana Tshirt",
            "slug": "solana-tshirt",
            "count": 37,
            "ext": "png"
          },
          {
            "name": "Censored",
            "slug": "none",
            "count": 12,
            "ext": "png"
          }
        ]
      },
      {
        "id": "eyes",
        "label": "Eyes",
        "metaName": "Eyes",
        "dir": "eyes",
        "optional": false,
        "noneCount": 0,
        "focus": {
          "x": 0.0608,
          "y": 0,
          "w": 0.9392,
          "h": 0.9392
        },
        "traits": [
          {
            "name": "Open",
            "slug": "open",
            "count": 591,
            "ext": "png"
          },
          {
            "name": "Close",
            "slug": "close",
            "count": 448,
            "ext": "png"
          },
          {
            "name": "Focused",
            "slug": "focused",
            "count": 443,
            "ext": "png"
          },
          {
            "name": "Hearth Sunglasses",
            "slug": "hearth-sunglasses",
            "count": 385,
            "ext": "png"
          },
          {
            "name": "Sleeping",
            "slug": "sleeping",
            "count": 384,
            "ext": "png"
          },
          {
            "name": "Hypnotize",
            "slug": "hypnotize",
            "count": 364,
            "ext": "png"
          },
          {
            "name": "Crying",
            "slug": "crying",
            "count": 363,
            "ext": "png"
          },
          {
            "name": "White Sunglasses",
            "slug": "white-sunglasses",
            "count": 313,
            "ext": "png"
          },
          {
            "name": "Red Sunglasses",
            "slug": "red-sunglasses",
            "count": 302,
            "ext": "png"
          },
          {
            "name": "Yellow Makeup",
            "slug": "yellow-makeup",
            "count": 297,
            "ext": "png"
          },
          {
            "name": "Cucumber",
            "slug": "cucumber",
            "count": 248,
            "ext": "png"
          },
          {
            "name": "Blue Makeup",
            "slug": "blue-makeup",
            "count": 195,
            "ext": "png"
          },
          {
            "name": "Hearth",
            "slug": "hearth",
            "count": 190,
            "ext": "png"
          },
          {
            "name": "Wink",
            "slug": "wink",
            "count": 186,
            "ext": "png"
          },
          {
            "name": "Red Makeup",
            "slug": "red-makeup",
            "count": 183,
            "ext": "png"
          },
          {
            "name": "Dollar Sign",
            "slug": "dollar-sign",
            "count": 72,
            "ext": "png"
          },
          {
            "name": "Laser",
            "slug": "laser",
            "count": 36,
            "ext": "png"
          }
        ]
      },
      {
        "id": "mouth",
        "label": "Mouth",
        "metaName": "Mouth",
        "dir": "mouth",
        "optional": false,
        "noneCount": 0,
        "focus": {
          "x": 0.3931,
          "y": 0.395,
          "w": 0.5683,
          "h": 0.5683
        },
        "traits": [
          {
            "name": "Smiling",
            "slug": "smiling",
            "count": 864,
            "ext": "png"
          },
          {
            "name": "Neutral",
            "slug": "neutral",
            "count": 843,
            "ext": "png"
          },
          {
            "name": "Disgusted",
            "slug": "disgusted",
            "count": 715,
            "ext": "png"
          },
          {
            "name": "Annoyed",
            "slug": "annoyed",
            "count": 713,
            "ext": "png"
          },
          {
            "name": "Cigarette",
            "slug": "cigarette",
            "count": 596,
            "ext": "png"
          },
          {
            "name": "Toothbrush",
            "slug": "toothbrush",
            "count": 540,
            "ext": "png"
          },
          {
            "name": "Lick",
            "slug": "lick",
            "count": 177,
            "ext": "png"
          },
          {
            "name": "Lip Biting",
            "slug": "lip-biting",
            "count": 175,
            "ext": "png"
          },
          {
            "name": "Lip Licking",
            "slug": "lip-licking",
            "count": 168,
            "ext": "png"
          },
          {
            "name": "Braces",
            "slug": "braces",
            "count": 107,
            "ext": "png"
          },
          {
            "name": "Bubble Gum",
            "slug": "bubble-gum",
            "count": 69,
            "ext": "png"
          },
          {
            "name": "Golden Teeth",
            "slug": "golden-teeth",
            "count": 33,
            "ext": "png"
          }
        ]
      },
      {
        "id": "hair",
        "label": "Hair",
        "metaName": "Hair",
        "dir": "hair",
        "optional": false,
        "noneCount": 0,
        "focus": {
          "x": 0.1394,
          "y": 0.1325,
          "w": 0.7693,
          "h": 0.7693
        },
        "traits": [
          {
            "name": "Purple Hair",
            "slug": "purple-hair",
            "count": 1095,
            "ext": "png"
          },
          {
            "name": "Blue Hair",
            "slug": "blue-hair",
            "count": 1083,
            "ext": "png"
          },
          {
            "name": "Yellow Hair",
            "slug": "yellow-hair",
            "count": 1071,
            "ext": "png"
          },
          {
            "name": "Red Hair",
            "slug": "red-hair",
            "count": 665,
            "ext": "png"
          },
          {
            "name": "Orange Hair",
            "slug": "orange-hair",
            "count": 640,
            "ext": "png"
          },
          {
            "name": "Pink Hair",
            "slug": "pink-hair",
            "count": 446,
            "ext": "png"
          }
        ]
      },
      {
        "id": "hats",
        "label": "Hat",
        "metaName": "Hats",
        "dir": "hats",
        "optional": true,
        "noneCount": 569,
        "focus": {
          "x": 0.2129,
          "y": 0,
          "w": 0.651,
          "h": 0.651
        },
        "traits": [
          {
            "name": "Green Hat",
            "slug": "green-hat",
            "count": 566,
            "ext": "png"
          },
          {
            "name": "Pink Hat",
            "slug": "pink-hat",
            "count": 566,
            "ext": "png"
          },
          {
            "name": "Purple Hat",
            "slug": "purple-hat",
            "count": 545,
            "ext": "png"
          },
          {
            "name": "Orange Cap",
            "slug": "orange-cap",
            "count": 434,
            "ext": "png"
          },
          {
            "name": "Blue Fascinator",
            "slug": "blue-fascinator",
            "count": 369,
            "ext": "png"
          },
          {
            "name": "Green Beret",
            "slug": "green-beret",
            "count": 365,
            "ext": "png"
          },
          {
            "name": "Party Hat",
            "slug": "party-hat",
            "count": 362,
            "ext": "png"
          },
          {
            "name": "Bear Cap",
            "slug": "bear-cap",
            "count": 354,
            "ext": "png"
          },
          {
            "name": "Tennis Cap",
            "slug": "tennis-cap",
            "count": 348,
            "ext": "png"
          },
          {
            "name": "Strawberry Cap",
            "slug": "strawberry-cap",
            "count": 185,
            "ext": "png"
          },
          {
            "name": "Bridal Crown",
            "slug": "bridal-crown",
            "count": 149,
            "ext": "png"
          },
          {
            "name": "Nurse Hat",
            "slug": "nurse-hat",
            "count": 74,
            "ext": "png"
          },
          {
            "name": "Rose Crown",
            "slug": "rose-crown",
            "count": 60,
            "ext": "png"
          },
          {
            "name": "Pink Halo",
            "slug": "pink-halo",
            "count": 36,
            "ext": "png"
          },
          {
            "name": "Crown",
            "slug": "crown",
            "count": 18,
            "ext": "png"
          }
        ]
      },
      {
        "id": "earring",
        "label": "Earring",
        "metaName": "Earring",
        "dir": "earring",
        "optional": true,
        "noneCount": 806,
        "focus": {
          "x": 0.013,
          "y": 0.3046,
          "w": 0.5,
          "h": 0.5
        },
        "traits": [
          {
            "name": "Daisy",
            "slug": "daisy",
            "count": 560,
            "ext": "png"
          },
          {
            "name": "Feather",
            "slug": "feather",
            "count": 537,
            "ext": "png"
          },
          {
            "name": "Cherry",
            "slug": "cherry",
            "count": 524,
            "ext": "png"
          },
          {
            "name": "Avacado",
            "slug": "avacado",
            "count": 517,
            "ext": "png"
          },
          {
            "name": "Dice",
            "slug": "dice",
            "count": 430,
            "ext": "png"
          },
          {
            "name": "Hearthrate",
            "slug": "hearthrate",
            "count": 416,
            "ext": "png"
          },
          {
            "name": "Pearls",
            "slug": "pearls",
            "count": 306,
            "ext": "png"
          },
          {
            "name": "Smiley",
            "slug": "smiley",
            "count": 268,
            "ext": "png"
          },
          {
            "name": "Rainbow",
            "slug": "rainbow",
            "count": 258,
            "ext": "png"
          },
          {
            "name": "Golder Flower",
            "slug": "golder-flower",
            "count": 162,
            "ext": "png"
          },
          {
            "name": "Diamond",
            "slug": "diamond",
            "count": 107,
            "ext": "png"
          },
          {
            "name": "Strawberry",
            "slug": "strawberry",
            "count": 74,
            "ext": "png"
          },
          {
            "name": "Solana",
            "slug": "solana",
            "count": 35,
            "ext": "png"
          }
        ]
      }
    ],
    "stack": [
      {
        "kind": "category",
        "categoryId": "background"
      },
      {
        "kind": "category",
        "categoryId": "body"
      },
      {
        "kind": "category",
        "categoryId": "clothes"
      },
      {
        "kind": "derived",
        "dir": "body-right-ear",
        "fromCategoryId": "body"
      },
      {
        "kind": "derived",
        "dir": "body-head",
        "fromCategoryId": "body"
      },
      {
        "kind": "category",
        "categoryId": "hair"
      },
      {
        "kind": "category",
        "categoryId": "hats"
      },
      {
        "kind": "derived",
        "dir": "body-left-ear",
        "fromCategoryId": "body"
      },
      {
        "kind": "category",
        "categoryId": "eyes"
      },
      {
        "kind": "category",
        "categoryId": "earring"
      },
      {
        "kind": "category",
        "categoryId": "mouth"
      }
    ],
    "codeOrder": [
      "background",
      "body",
      "clothes",
      "earring",
      "eyes",
      "hair",
      "hats",
      "mouth"
    ],
    "codeHash": "d32e1940ec8b",
    "defaultLook": "00000000",
    "heroLook": "65IB5219",
    "rarityCurve": [
      6.264,
      6.65,
      6.731,
      6.793,
      6.839,
      6.883,
      6.917,
      6.945,
      6.977,
      7.004,
      7.028,
      7.045,
      7.064,
      7.088,
      7.105,
      7.124,
      7.147,
      7.164,
      7.183,
      7.2,
      7.218,
      7.234,
      7.249,
      7.263,
      7.278,
      7.295,
      7.312,
      7.327,
      7.345,
      7.363,
      7.38,
      7.399,
      7.416,
      7.433,
      7.446,
      7.457,
      7.474,
      7.491,
      7.506,
      7.521,
      7.541,
      7.553,
      7.566,
      7.578,
      7.592,
      7.605,
      7.62,
      7.64,
      7.656,
      7.666,
      7.681,
      7.695,
      7.711,
      7.727,
      7.742,
      7.758,
      7.774,
      7.792,
      7.806,
      7.824,
      7.845,
      7.864,
      7.882,
      7.898,
      7.917,
      7.932,
      7.952,
      7.97,
      7.989,
      8.01,
      8.035,
      8.06,
      8.081,
      8.101,
      8.127,
      8.149,
      8.171,
      8.194,
      8.215,
      8.24,
      8.266,
      8.298,
      8.326,
      8.353,
      8.38,
      8.41,
      8.451,
      8.497,
      8.526,
      8.564,
      8.614,
      8.676,
      8.737,
      8.81,
      8.877,
      8.961,
      9.055,
      9.165,
      9.335,
      9.612,
      10.787
    ],
    "tokens": {
      "path": "/piggy/piggy-girl-gang/tokens.txt",
      "stride": 11,
      "firstId": 1,
      "count": 5000
    }
  },
  "piggy-gang": {
    "slug": "piggy-gang",
    "supply": 10000,
    "canvas": 2000,
    "bodyCategoryId": "body",
    "mannequinBody": "pink",
    "categories": [
      {
        "id": "background",
        "label": "Background",
        "metaName": "Background",
        "dir": "background",
        "optional": false,
        "noneCount": 0,
        "focus": {
          "x": 0,
          "y": 0,
          "w": 1,
          "h": 1
        },
        "traits": [
          {
            "name": "Red",
            "slug": "red",
            "count": 1486,
            "ext": "png"
          },
          {
            "name": "Purple",
            "slug": "purple",
            "count": 1456,
            "ext": "png"
          },
          {
            "name": "Yellow",
            "slug": "yellow",
            "count": 1436,
            "ext": "png"
          },
          {
            "name": "Cyan",
            "slug": "cyan",
            "count": 1433,
            "ext": "png"
          },
          {
            "name": "Blue",
            "slug": "blue",
            "count": 1418,
            "ext": "png"
          },
          {
            "name": "Orange",
            "slug": "orange",
            "count": 1390,
            "ext": "png"
          },
          {
            "name": "Green",
            "slug": "green",
            "count": 1381,
            "ext": "png"
          }
        ]
      },
      {
        "id": "special",
        "label": "Special",
        "metaName": "Earring",
        "dir": "special",
        "optional": true,
        "noneCount": 5639,
        "focus": {
          "x": 0,
          "y": 0.4,
          "w": 0.55,
          "h": 0.55
        },
        "traits": [
          {
            "name": "Mr. Lovo",
            "slug": "mr-lovo",
            "count": 1002,
            "ext": "png"
          },
          {
            "name": "Wingman",
            "slug": "wingman",
            "count": 1002,
            "ext": "png"
          },
          {
            "name": "Smoke",
            "slug": "smoke",
            "count": 936,
            "ext": "png"
          },
          {
            "name": "Angel Wings",
            "slug": "angel-wings",
            "count": 810,
            "ext": "png"
          },
          {
            "name": "Shotgun",
            "slug": "shotgun",
            "count": 611,
            "ext": "png"
          }
        ]
      },
      {
        "id": "body",
        "label": "Skin",
        "metaName": "Body | Received Mud",
        "dir": "body",
        "optional": false,
        "noneCount": 0,
        "focus": {
          "x": 0,
          "y": 0.0049,
          "w": 0.9951,
          "h": 0.9951
        },
        "traits": [
          {
            "name": "Salmon",
            "slug": "salmon",
            "count": 2860,
            "ext": "png"
          },
          {
            "name": "Pink",
            "slug": "pink",
            "count": 1648,
            "ext": "png"
          },
          {
            "name": "Dino",
            "slug": "dino",
            "count": 1609,
            "ext": "png"
          },
          {
            "name": "Leopard",
            "slug": "leopard",
            "count": 1406,
            "ext": "png"
          },
          {
            "name": "Mud Splash",
            "slug": "mud-splash",
            "count": 984,
            "ext": "png"
          },
          {
            "name": "Boar",
            "slug": "boar",
            "count": 589,
            "ext": "png"
          },
          {
            "name": "Zombie",
            "slug": "zombie",
            "count": 468,
            "ext": "png"
          },
          {
            "name": "Alien",
            "slug": "alien",
            "count": 293,
            "ext": "png"
          },
          {
            "name": "Solana",
            "slug": "solana",
            "count": 143,
            "ext": "png"
          }
        ]
      },
      {
        "id": "clothes",
        "label": "Clothes",
        "metaName": "Clothes",
        "dir": "clothes",
        "optional": true,
        "noneCount": 653,
        "focus": {
          "x": 0,
          "y": 0,
          "w": 1,
          "h": 1
        },
        "traits": [
          {
            "name": "Singlet",
            "slug": "singlet",
            "count": 1438,
            "ext": "png"
          },
          {
            "name": "Hoodie",
            "slug": "hoodie",
            "count": 1361,
            "ext": "png"
          },
          {
            "name": "Tux",
            "slug": "tux",
            "count": 1162,
            "ext": "png"
          },
          {
            "name": "Tracksuit",
            "slug": "tracksuit",
            "count": 832,
            "ext": "png"
          },
          {
            "name": "Biker Leather Jacket",
            "slug": "biker-leather-jacket",
            "count": 821,
            "ext": "png"
          },
          {
            "name": "Prison Suit",
            "slug": "prison-suit",
            "count": 720,
            "ext": "png"
          },
          {
            "name": "Butcher's Apron",
            "slug": "butcher-s-apron",
            "count": 718,
            "ext": "png"
          },
          {
            "name": "Hawaiian Tee",
            "slug": "hawaiian-tee",
            "count": 668,
            "ext": "png"
          },
          {
            "name": "Bone Necklace",
            "slug": "bone-necklace",
            "count": 555,
            "ext": "png"
          },
          {
            "name": "Pimp Coat",
            "slug": "pimp-coat",
            "count": 427,
            "ext": "png"
          },
          {
            "name": "Cyberpunk Jacket",
            "slug": "cyberpunk-jacket",
            "count": 293,
            "ext": "png"
          },
          {
            "name": "Blanket",
            "slug": "blanket",
            "count": 201,
            "ext": "png"
          },
          {
            "name": "Solana Tee",
            "slug": "solana-tee",
            "count": 151,
            "ext": "png"
          }
        ]
      },
      {
        "id": "head",
        "label": "Headwear",
        "metaName": "Head",
        "dir": "head",
        "optional": true,
        "noneCount": 581,
        "focus": {
          "x": 0.1295,
          "y": 0,
          "w": 0.8426,
          "h": 0.8426
        },
        "traits": [
          {
            "name": "Beanie",
            "slug": "beanie",
            "count": 846,
            "ext": "png"
          },
          {
            "name": "Chef's Hat",
            "slug": "chef-s-hat",
            "count": 749,
            "ext": "png"
          },
          {
            "name": "Cowboy Hat",
            "slug": "cowboy-hat",
            "count": 631,
            "ext": "png"
          },
          {
            "name": "Cap",
            "slug": "cap",
            "count": 575,
            "ext": "png"
          },
          {
            "name": "Pork Patrol",
            "slug": "pork-patrol",
            "count": 561,
            "ext": "png"
          },
          {
            "name": "Biker Hat",
            "slug": "biker-hat",
            "count": 554,
            "ext": "png"
          },
          {
            "name": "Straw Hat",
            "slug": "straw-hat",
            "count": 541,
            "ext": "png"
          },
          {
            "name": "Trucker Hat",
            "slug": "trucker-hat",
            "count": 531,
            "ext": "png"
          },
          {
            "name": "Dreads",
            "slug": "dreads",
            "count": 528,
            "ext": "png"
          },
          {
            "name": "Durag",
            "slug": "durag",
            "count": 525,
            "ext": "png"
          },
          {
            "name": "Pirate Hat",
            "slug": "pirate-hat",
            "count": 496,
            "ext": "png"
          },
          {
            "name": "Mohawk",
            "slug": "mohawk",
            "count": 470,
            "ext": "png"
          },
          {
            "name": "Pimp Hat",
            "slug": "pimp-hat",
            "count": 443,
            "ext": "png"
          },
          {
            "name": "Robohawk",
            "slug": "robohawk",
            "count": 348,
            "ext": "png"
          },
          {
            "name": "Fly Halo",
            "slug": "fly-halo",
            "count": 329,
            "ext": "png"
          },
          {
            "name": "Bucket Hat",
            "slug": "bucket-hat",
            "count": 232,
            "ext": "png"
          },
          {
            "name": "Medusa",
            "slug": "medusa",
            "count": 231,
            "ext": "png"
          },
          {
            "name": "Hawk's Nest",
            "slug": "hawk-s-nest",
            "count": 223,
            "ext": "png"
          },
          {
            "name": "Propeller Hat",
            "slug": "propeller-hat",
            "count": 214,
            "ext": "png"
          },
          {
            "name": "Halo",
            "slug": "halo",
            "count": 122,
            "ext": "png"
          },
          {
            "name": "Unicorn",
            "slug": "unicorn",
            "count": 110,
            "ext": "png"
          },
          {
            "name": "Ice Cream",
            "slug": "ice-cream",
            "count": 109,
            "ext": "png"
          },
          {
            "name": "Royal Crown",
            "slug": "royal-crown",
            "count": 51,
            "ext": "png"
          }
        ]
      },
      {
        "id": "eyes",
        "label": "Eyes",
        "metaName": "Eyes",
        "dir": "eyes",
        "optional": false,
        "noneCount": 0,
        "focus": {
          "x": 0.2163,
          "y": 0.1477,
          "w": 0.7837,
          "h": 0.7837
        },
        "traits": [
          {
            "name": "Open",
            "slug": "open",
            "count": 1176,
            "ext": "png"
          },
          {
            "name": "Scar",
            "slug": "scar",
            "count": 976,
            "ext": "png"
          },
          {
            "name": "Pimp Glasses",
            "slug": "pimp-glasses",
            "count": 968,
            "ext": "png"
          },
          {
            "name": "Tear Drop Tattoos",
            "slug": "tear-drop-tattoos",
            "count": 758,
            "ext": "png"
          },
          {
            "name": "High",
            "slug": "high",
            "count": 712,
            "ext": "png"
          },
          {
            "name": "Wink",
            "slug": "wink",
            "count": 702,
            "ext": "png"
          },
          {
            "name": "Viper Glasses",
            "slug": "viper-glasses",
            "count": 690,
            "ext": "png"
          },
          {
            "name": "Focused",
            "slug": "focused",
            "count": 680,
            "ext": "png"
          },
          {
            "name": "Coin",
            "slug": "coin",
            "count": 668,
            "ext": "png"
          },
          {
            "name": "White Glow",
            "slug": "white-glow",
            "count": 575,
            "ext": "png"
          },
          {
            "name": "Terminator",
            "slug": "terminator",
            "count": 489,
            "ext": "png"
          },
          {
            "name": "Urban Frames Glasses",
            "slug": "urban-frames-glasses",
            "count": 486,
            "ext": "png"
          },
          {
            "name": "Pork Patrol",
            "slug": "pork-patrol",
            "count": 478,
            "ext": "png"
          },
          {
            "name": "Dollar Sign Glasses",
            "slug": "dollar-sign-glasses",
            "count": 246,
            "ext": "png"
          },
          {
            "name": "Oinkulus",
            "slug": "oinkulus",
            "count": 245,
            "ext": "png"
          },
          {
            "name": "Laser",
            "slug": "laser",
            "count": 151,
            "ext": "png"
          }
        ]
      },
      {
        "id": "earring",
        "label": "Earring",
        "metaName": "Earring",
        "dir": "earring",
        "optional": true,
        "noneCount": 6741,
        "focus": {
          "x": 0,
          "y": 0.2193,
          "w": 0.5,
          "h": 0.5
        },
        "traits": [
          {
            "name": "Diamond",
            "slug": "diamond",
            "count": 1021,
            "ext": "png"
          },
          {
            "name": "Ear Tag",
            "slug": "ear-tag",
            "count": 999,
            "ext": "png"
          },
          {
            "name": "Gold Ring",
            "slug": "gold-ring",
            "count": 604,
            "ext": "png"
          },
          {
            "name": "Pink Diamond",
            "slug": "pink-diamond",
            "count": 435,
            "ext": "png"
          },
          {
            "name": "Solana",
            "slug": "solana",
            "count": 200,
            "ext": "png"
          }
        ]
      },
      {
        "id": "mouth",
        "label": "Mouth",
        "metaName": "Mouth",
        "dir": "mouth",
        "optional": false,
        "noneCount": 0,
        "focus": {
          "x": 0.0979,
          "y": 0.0979,
          "w": 0.9021,
          "h": 0.9021
        },
        "traits": [
          {
            "name": "Smiling",
            "slug": "smiling",
            "count": 1506,
            "ext": "png"
          },
          {
            "name": "Neutral",
            "slug": "neutral",
            "count": 1501,
            "ext": "png"
          },
          {
            "name": "Nose Ring",
            "slug": "nose-ring",
            "count": 1096,
            "ext": "png"
          },
          {
            "name": "Muzzle",
            "slug": "muzzle",
            "count": 1035,
            "ext": "png"
          },
          {
            "name": "Cigarette",
            "slug": "cigarette",
            "count": 870,
            "ext": "png"
          },
          {
            "name": "Blunt",
            "slug": "blunt",
            "count": 846,
            "ext": "png"
          },
          {
            "name": "Apple",
            "slug": "apple",
            "count": 831,
            "ext": "png"
          },
          {
            "name": "Coin",
            "slug": "coin",
            "count": 683,
            "ext": "png"
          },
          {
            "name": "Butcher's Knife",
            "slug": "butcher-s-knife",
            "count": 585,
            "ext": "png"
          },
          {
            "name": "Diamond Grills",
            "slug": "diamond-grills",
            "count": 448,
            "ext": "png"
          },
          {
            "name": "Pipe",
            "slug": "pipe",
            "count": 433,
            "ext": "png"
          },
          {
            "name": "Golden Teeth",
            "slug": "golden-teeth",
            "count": 166,
            "ext": "png"
          }
        ]
      }
    ],
    "stack": [
      {
        "kind": "category",
        "categoryId": "background"
      },
      {
        "kind": "category",
        "categoryId": "special"
      },
      {
        "kind": "category",
        "categoryId": "body"
      },
      {
        "kind": "category",
        "categoryId": "clothes"
      },
      {
        "kind": "category",
        "categoryId": "head"
      },
      {
        "kind": "category",
        "categoryId": "eyes"
      },
      {
        "kind": "category",
        "categoryId": "earring"
      },
      {
        "kind": "category",
        "categoryId": "mouth"
      }
    ],
    "codeOrder": [
      "background",
      "body",
      "clothes",
      "earring",
      "eyes",
      "head",
      "mouth",
      "special"
    ],
    "codeHash": "f4bbbfabaa6d",
    "defaultLook": "00100100",
    "heroLook": "58D47JB0",
    "rarityCurve": [
      5.641,
      6.002,
      6.106,
      6.184,
      6.245,
      6.295,
      6.342,
      6.4,
      6.45,
      6.492,
      6.533,
      6.571,
      6.609,
      6.648,
      6.678,
      6.71,
      6.739,
      6.761,
      6.788,
      6.816,
      6.84,
      6.867,
      6.888,
      6.905,
      6.924,
      6.947,
      6.968,
      6.989,
      7.009,
      7.028,
      7.047,
      7.064,
      7.078,
      7.095,
      7.112,
      7.126,
      7.141,
      7.155,
      7.171,
      7.188,
      7.203,
      7.217,
      7.232,
      7.244,
      7.258,
      7.275,
      7.29,
      7.304,
      7.319,
      7.331,
      7.346,
      7.361,
      7.377,
      7.391,
      7.408,
      7.42,
      7.433,
      7.448,
      7.465,
      7.481,
      7.493,
      7.508,
      7.523,
      7.54,
      7.556,
      7.572,
      7.589,
      7.604,
      7.622,
      7.638,
      7.657,
      7.674,
      7.694,
      7.717,
      7.734,
      7.753,
      7.775,
      7.795,
      7.814,
      7.836,
      7.863,
      7.889,
      7.912,
      7.934,
      7.959,
      7.991,
      8.017,
      8.051,
      8.082,
      8.113,
      8.147,
      8.185,
      8.223,
      8.267,
      8.316,
      8.379,
      8.466,
      8.565,
      8.666,
      8.848,
      10.75
    ],
    "tokens": {
      "path": "/piggy/piggy-gang/tokens.txt",
      "stride": 11,
      "firstId": 1,
      "count": 10000
    }
  }
};
